# PW 4:  Arrays, **NumPy** library 



## 1 - **NumPy** library

### 1.1 - Definition

- **NumPy** is a Python digital library for handling arrays. It allows you to work with the mathematical functions used with these tables. 

### 1.2 - Using **NumPy**

- ** NumPy ** is a python library. It must be imported before it can be used. For ease of use, it will be imported under the alias `np`: 

```python
import numpy as np
```
- This import is done only once. It is thus generally placed at the start of the program or the notebook.
- The elements of the library (functions, constants, *etc*), are called via the keyword  `np`
```python
print(np.sqrt(x))
print(np.pi)
```
- For a simple writing of algorithms, many mathematical functions have been implemented. For more details on the basic functions of **NumPy**, see https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs. Some constants (like $ \ pi $) are also defined. 

---
**Exercise:** Using the features of the **NumPy** library, calculate and display:  
- $\pi$
- The square root of 9.
- the tangent of $\pi$, sine and cosine of $\frac{\pi}{4}$.
- $ e $ the base of the logarithm, the logarithm  of $ e $ and the exponential and the logarithm of 1.


---


## 2 - Arrays

- One of the main features of the **NumPy** library is the arrays creation and manipulation. 
- An array is a new type named **numpy.ndarray** defined by this library. 
- Tables are very useful tools for programming, for scientific calculation and data management:
    - they can for example be used with the functions defined above;
    - they can be used to store data from files;
    - they can be used to save and read data in files. 

### 2.1 - Definitions

Several ways exist to define a **Numpy** Array (non-exhaustive list):


- using the `array` function. The `list` from which the array is taken, is one of the arguments.
```python
lis = [1, 2, 3]
tab = np.array(lis)
# or, more directly, 
tab = np.array([1, 2, 3])
```
- using the function `zeros` or `ones`. The **integer** representing the number of elements of the array (its length) is given as an argument.
```python
np.zeros(20)
np.ones(20)
```
- using the function  `arange`. The starting value `N1`(included), the end value` N2`(excluded) and the step `p`, which can be integer or real, are given as arguments.
```Python
tab = np.arange(N1, N2, p) 
```
- `N1` and `p` are optional and will default to 0 and 1, respectively, if not given. Otherwise you will have to specify these values. For an array starting with `2` and ending with` N2` (excluded value) with a step of `2`, for example, we will have: 
```Python
tab = np.arange(2, N2, 2)
```

---
**Exercises:** Execute the different cells and create a markdown cell below to explain the functionnality and what the short code is doing:



In [2]:
lis1 = [6, 7, 8, 9, 10]
print("lis1 =", lis1)
a1 = np.array(lis1)
print("a1 =",a1)

lis1 = [6, 7, 8, 9, 10]
a1 = [ 6  7  8  9 10]


In [3]:
a2 = np.array([1, 2, 3, 4, 5])
print("a2 =", a2)

a2 = [1 2 3 4 5]


In [4]:
a3 = np.array([True, True, False])
print("a3 =", a3)

a3 = [ True  True False]


In [5]:
a4 = np.zeros(20)
print("a4 =", a4)

a4 = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
a5 = np.ones(100)
print("a5 =", a5)

a5 = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [7]:
a6 = np.arange(11)
print("a6 =", a6)

a6 = [ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
a7 = np.arange(0, 1, 0.2)
print("a7 =", a7)

a7 = [0.  0.2 0.4 0.6 0.8]


---

### 2.2 - Operations

- One of the great advantages of **NumPy** is that the functions presented in section 1 are applicable to arrays. We can thus apply the function on the array as a whole rather than element by element.
- The result returned by the function is itself an array of the same length as the argument array of the function. The values in this array are the results of the operation on each of the elements,row by row.
- The usual operations (addition, subtraction, multiplication, etc.) are also applicable to tables. 

---
**Exercises:** Execute the different cells and create a markdown cell below to explain the functionnality and what the short code is doing:


In [4]:
b1 = 4 * np.ones(5)
print("b1 =", b1)

b1 = [4. 4. 4. 4. 4.]


In [5]:
b2 = np.sqrt(b1)
print("b2 =", b2)

b2 = [2. 2. 2. 2. 2.]


In [6]:
b3 = b1 + b2
print("b3 =", b3)

b3 = [6. 6. 6. 6. 6.]


In [7]:
b4 = b1 * b2
print("b4 =", b4)

b4 = [8. 8. 8. 8. 8.]


---

### 2.3 - Input / output file 

- It is possible to save an array **NumPy** in a binary file with the extension **.npy**. Conversely, the content of files with the **.npy** extension can be read and stored in **NumPy** arrays. For these operations, the `save` and` load` functions are used. 
```python
np.save("name.npy",array1)
array2 = np.load("name.npy")
```
---
**Exercise:** 
- save the array `b4` in a file caled **temp.npy**
- load and display **temp.npy** in an array `b5`
- Check the presence of the file thus created in the Jupyterlab file browser (the left column). Be careful, do not try to open this binary file directly by clicking on it! 

- Although the binary format is more efficient for storing large arrays, it is actually often more convenient, if the size of the tables is reasonable, to save them in text format.
- As for the binary, the **NumPy** library offers a function for writing a file in text format `savetxt` and one for reading` loadtxt`.
- The file extension used in this case is usually **.txt** or **.dat**.

---
**Exercise:** Repeat the previous exercise but this time using the text format (with the file extension **.txt**). 

### 2.4 - Two-dimensional arrays

The ** NumPy ** library also allows you to handle 2-dimensional arrays. Note: there are matrix type variables, `numpy.matrix`, which should not be confused with these arrays. 
The method of creating 2-dimensional arrays is very similar to that of one-dimensional arrays. The same function -`array` - is used, only the arguments are different. 
- For a n rows and p columns array, it is necessary to give as argument of the function `array` a list of n lists, each of length p. This is an example fo an array of 2 rows and 3 colums. Pay attention to the succession `([ [ ],[ ] ])`. The order is always the same; **the number (or index) of rows first, the number (or index) of column, second**.

```python
pi=np.pi
neper=np.e
arr1 = np.array([[1, 2, 3], [pi, neper, 7]])
```
- with the `zeros` or` ones` functions, the argument is a list that contains the number of rows and the number of columns (in that order). 
```python
dim = [20, 10]
arr2 = np.zeros(dim)
arr3 = np.ones(dim)
```
- The `reshape` function allows you to reorganise the display of the elements of an array by varying its dimensions. The `reshape`'s arguments are: the array to modify, the list of dimensions of the new array. 
``` Python
arr4 = np.zeros(200)
dim = [20, 10]
arr5 = np.reshape(arr4, dim) 
```
- `reshape` considers that all the elements of the array form a single sequence which is broken down into pieces of length the number of columns. The total number of elements remains constant. 

---
**Exercises:** In different cells:
- Create an array `c1` with 3 rows and 4 columns using the function` array` and a list. Display them.
- Create an array with 3 rows and 2 columns in a variable `c2` using the` zeros` function. Display it.
- Transform the previous 2 arrays respectively into a `c3` array with 4 rows and 3 columns and a ` c4` with two rows and three columns. Display them. Can we transform `c1` into an array with two lines and three columns? 

### 2.5 - Random numbers

- The NumPy library is equiped with a random number generator, a sub-library of NumPy, called **random**. It allows you to draw numbers randomly according to certain distributions. Several functions can be used, the main ones being:
    - **randint** which allows to draw N integers between 2 limits (the upper limit being excluded).
    - **random** which allows to draw N reals between 0 (included) and 1 (excluded).
    - **uniform** which allows to draw N real values between 2 limits (the upper limit being excluded).
```python
arr4 = np.random.randint(lowerbound, upperbound, N)
arr5 = np.random.random(N)
arr6 = np.random.uniform(lowerbound, upperbound, N)
```


- If the number `N` is given as a list of two integers, ** NumPy ** generates a two-dimensional array of lengths corresponding to the values in the list. 
```python
arr7 = np.random.randint(lowerbound, upperbound, [3, 4])
```


- For more information on the module  **random**, see https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

---
**Exercises:**
- create and display an array `ran1` of 10 random reals between 0 included and 1 excluded.
- create and display an array `ran2` of 10 real numbers between 0 included and 100 excluded.
- create and display a two-dimensional `ran3` array of 5$\times$5 integers between 0 inclusive and 100 excluded.

*Note : run cells multiple times and see the value changes.*

---

### 2.6 Indexing arrays

- An element of index `i` of an one dimensional **NumPy** array is selected by writing the name of the array followed by the index of the element enclosed in square brackets. 

- It is also possible to extract a sub-array included between the indices `i1` (included) and` i2` (excluded) by separating them with `:`.
    - By default, if no value of `i1` is given, it is set to the value 0. If no value for` i2` is given, it is set by default to the length of the array.
    - - The last value of the array can be indexed with the index -1, the penultimate with -2 and so on.
```Python
print(arr[0]) # displays the first element of an array
print(arr[i1:i2]) # displays elements between indices i1 (included) and i2 (excluded)
print(arr[:i2]) # displays elements between indices 0 (included) and i2 (excluded)
print(arr[i1:]) # displays all array elements from index i1 (included) and above
```

---
**Exercise:** Define an array of 10 integers of your choice `d1`. Display different sub array for different values of i1 and i2 (including -1 and -2). What is the equivalent of the statement: `` print (d1 [:]) `` (answer in a cell). 


---
- It is also possible to index 2-dimensional arrays following the same principle.
- The indexation by dimension is then separated by a `,`
-  we also indicate to take all the elements of a row or a column with `:`. 
```Python
tab_2d[l1, c1] # displays the element at the intersection of the row with indexs l1 and the column with index c1 
tab_2d[l1:l2, c1:c2] # displays the sub-array between the lines l1 (included) and l2 (excluded) and the columns c1 (included) and c2 (excluded) 
tab_2d[l1, :] # displays all the columns of the index row l1 
tab_2d[:, c1] # displays all the rows of the column with index c1. 
```
---

**Exercise:**
- Display the second element of the third row of the array `ran3`.
- Display the antepenultimate row of the array `ran3`.
- Display the antepenultimate column of the `ran3` table.
- Store and display a variable `d2` the two-dimensional array corresponding to the last two rows and last two columns of the array` ran3`.


---

### 2.7 Arrays manipulation 
- The library **NumPy** proposes a set of functions acting directly on the totality of a table (with 1 or more dimensions.

- Sum and product:
     - The `sum` and `prod` functions. They take an array as argument and calculate and return the sum and the product of its elements, respectively.
     - In the case of a two-dimensional array, it is possible to pass the optional argument `axis` which will take the value 0 to calculate the sum (or the product, depending on the function used) of the rows, and 1 to perform the calculations on the columns. 
     
     Example:
``` Python
np.sum (array, axis = 0)
```     
---
**Exercise:**
Execute the different cells and create a markdown cell below to explain the functionnality and what the short code is doing:


In [24]:
m1 = np.arange(1, 11)
print(np.sum(m1))
print(np.prod(m1))

55
3628800


In [25]:
m2 = np.arange(15)
m2 = np.reshape(m2, [3, 5])
print(m2)
print(np.sum(m2, axis=0))
print(np.sum(m2, axis=1))
print(np.sum(m2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[15 18 21 24 27]
[10 35 60]
105


---